### PR TITLE
feat: Post to backend

### PR DESCRIPTION
**Pull request by ishiasaka**

### CODE REVIEW

**Comment by premepreme** [comment]
Screen Shot 2566-02-10 at 18 33 49
i got error

**Comment by premepreme** [comment]
cannot input #board `[](url)`

**Comment by premepreme** [comment]
cannot cilk on submit button and not thing happen

**Comment by ishiasaka** [comment]
> cannot cilk on submit button and not thing happen

https://github.com/Exceed19-Group14/project-frontend-2/commit/08fb8568fece9e42471744cc7671d85cf00b0ff3
In this file you can use set `axios.default.baseUrl` for fetch in exceed server

**Pull request merged**
